server:
  port: 8080

eureka:
  client:
    enabled: false

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  kafka:
    bootstrap-servers: kafka-service:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
  config:
    activate:
      on-profile: prod
  application:
    name: drive-service
  redis:
    host: redis-service
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}/synco
    username: admin
    password: ${DB_PW}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show__sql: true
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: synco-bucket

jwt:
  expirationAt: 10000
  secretKeyAt: ${JWT_SECRET_KEY_AT}
  expirationRt: 10000
  secretKeyRt: ${JWT_SECRET_KEY_RT}

## Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true